import { AuthProvider } from "@/helpers/AuthContext ";
import "./globals.css";


export const metadata = {
  title: "WebCareCircle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
     

      <body >
      <AuthProvider>
        {children}
      </AuthProvider>
        </body>
    </html>
  );
}
